version: 2
jobs:
  build:
    docker:
      - image: adamantium/flutter:dev
    steps:
      - checkout
      - run: flutter doctor && cd attendance_admin && flutter packages get && flutter test && flutter -v build apk --debug
